### ISSUE TITLE
Image Search Returns Error Sometimes

### ISSUE THREAD

**Issue by jsills3110** [jsills3110/Project-1#46]
### Issue(s)

- On some flickr api searches, the following error is returned and no image is displayed: 
**jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'farm' of undefined TypeError: Cannot read property 'farm' of undefined**
    at displayImage (file:///C:/Users/Jessica/OneDrive/Documents/UWCodingBootcamp/Project-1/assets/javascript/images.js:18:36)
    at Object.<anonymous> (file:///C:/Users/Jessica/OneDrive/Documents/UWCodingBootcamp/Project-1/assets/javascript/images.js:10:9)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js:2:29453)
    at t (https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js:2:29755) undefined

**Comment by dima-04** [comment]
thanks jess for the report,
this happened when we try to show one image.
this should be resolved with my last change to show related images.
